announcement:
  class: sfPropelRouteCollection
  options:
    model:                Announcement
    module:               announcement
    prefix_path:          /announcement
    column:               id
    with_wildcard_routes: true

render_attachment:
  url: /attachments/:id.png
  class: sfPropelRoute
  options: { model: FileAttachment, type: object }
  param: { module: attachment, action: render }

delete_attachment:
  url: /attachments/:id.png/delete
  class: sfPropelRoute
  options: { model: FileAttachment, type: object }
  param: { module: attachment, action: delete }

property:
  class: sfPropelRouteCollection
  options:
    model:                Property
    module:               property
    prefix_path:          property
    column:               id
    with_wildcard_routes: true

# default rules
homepage:
  url:   /
  param: { module: property, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
