default:
  http_metas:
    content-type: text/html

  metas:
    title:        Citad'in - Interface d'administration
    #description:  symfony project
    #keywords:     symfony, project
    language:     fr
    robots:       noindex, nofollow

  stylesheets:    [main.css, thumbnail_list.css]

  javascripts:    [jquery, backend-filters]

  has_layout:     true
  layout:         layout
