default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css, thumbnail_list.css]

  javascripts:    [jquery, backend-filters]

  has_layout:     true
  layout:         layout
