# default values
all:
  contact:
    address: 57, rue de la thibaudière 69007 LYON
    mobile: "0648471616"
    phone: "0950441951"
    fax: "0955441951"

  emails:
    from_name: { contact@citadin.fr: "L'équipe citad'in" }
    assisted_search_subject: "Nous avons bien reçu votre demande"
    assisted_search_notice_subject: "Y'a un mec qui veut un appart !"
    send_notices_to: { mirsal.ennaime@gmail.com: Mirsal Ennaime }
    submit_property_subject: "Nous avons bien reçu votre demande"
    submit_property_notice_subject: "Une demande d'ajout de bien a été déposée"
