contact:
  url: /contact
  param: { module: contact, action: index }

property_index:
  url: /property
  param: { module: property, action: index }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
