contact:
  url: /contact
  param: { module: contact, action: index }

property_index:
  url: /property
  param: { module: property, action: index }

property_show:
  url: /property/:id
  class: sfPropelRoute
  options: { model: Property, type: object }
  param: { module: property, action: show }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
