search_manual:
  url: /search_manual
  param: { module: search, action: manual }

contact:
  url: /contact
  param: { module: contact, action: index }

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
