render_attachment:
  url: /attachments/:id.png
  class: sfPropelRoute
  options: { model: FileAttachment, type: object }
  param: { module: attachment, action: render }

contact:
  url: /contact
  param: { module: contact, action: index }

property_index:
  url: /property
  param: { module: property, action: index }

add_property_filter:
  url: /property/add_filter
  param: { module: property, action: addFilter }

update_property_page_length:
  url: /property/update_page_length
  param: { module: property, action: updatePageLength }

property_show:
  url: /property/:id
  class: sfPropelRoute
  options: { model: Property, type: object }
  param: { module: property, action: show }
  requirements:
    id: \d+

# default rules
homepage:
  url:   /
  param: { module: home, action: index }

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
