default:
  http_metas:
    content-type: text/html

  metas:
    title:        Citad'in agence immobilière à Lyon
    description:  Citad'in est une agence immobilière basée à Lyon
    keywords:     citadin, immobilier, vente, location, appartements
    language:     fr
    robots:       index, follow

  stylesheets:    [main.css, layout.css, common.css]

  javascripts:    [jquery]

  has_layout:     true
  layout:         layout
