dev:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  DebugPDO
      dsn:        mysql:dbname=citadin;host=localhost
      username:   citadin
      password:   citadin
      encoding:   utf8
      persistent: true
      pooling:    true

prod:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=citadin;host=db-pre-prod
      username:   citadin
      password:
      encoding:   utf8
      persistent: true
      pooling:    true