propel:
  property:
    _attributes:  { phpName: Property }
    id:
    created_at:
    name:         { type: varchar(128), required: true }
    location:     { type: varchar(255), required: true }
    type:         { type: varchar(64), required: true }
    description:  { type: longvarchar }
    price:        { type: integer }
    surface:      { type: integer }
    rooms:        { type: integer }
    bedrooms:     { type: integer }
    orientation:  { type: varchar(128) }
    garage:       { type: boolean }
    parking:      { type: boolean }
    balcony:      { type: boolean }
    terrace:      { type: boolean }
    cellar:       { type: boolean }
    attic:        { type: boolean }
    is_activated: { type: boolean }

  file_attachment:
    _attributes: { phpName: FileAttachment }
    id:
    property_id: { type: integer, foreignTable: property, foreignReference: id, onDelete: cascade, index: true }
    file_attachment_id: { type: integer, foreignTable: file_attachment, foreignReference: id, onDelete: cascade, index: true }
    relative_size: { type: varchar(16), index: true }
    content_type: varchar(32)
    size: integer
    data: blob

  customer:
    _attributes:  { phpName: Customer }
    user_id:      { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    email:        { type: varchar(128), required: true }
    name:         { type: varchar(128), required: true }
    address:      { type: varchar(255), required: false }
    postal_code:  { type: varchar(16), required: false }
    home_phone:   { type: varchar(16), required: false } 
    mobile_phone: { type: varchar(16), required: false }
