propel:
  property:
    _attributes:  { phpName: Property }
    id:
    name:         { type: varchar(128), required: true }
    location:     { type: varchar(255), required: true }
    type:         { type: varchar(64), required: true }
    price:        { type: integer }
    description:  { type: longvarchar }
    surface:      { type: integer }
    orientation:  { type: varchar(128) }

  customer:
    _attributes:  { phpName: Customer }
    user_id:      { type: integer, foreignTable: sf_guard_user, foreignReference: id, required: true, onDelete: cascade }
    email:        { type: varchar(128), required: true }
    name:         { type: varchar(128), required: true }
    address:      { type: varchar(255), required: false }
    postal_code:  { type: varchar(16), required: false }
    home_phone:   { type: varchar(16), required: false } 
    mobile_phone: { type: varchar(16), required: false }