generator:
  class: sfPropelGenerator
  param:
    model_class:           Property
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          property
    with_propel_route:     1

    config:
      actions: ~
      fields:
          created_at: { label: Date d'ajout }
          name:       { label: Nature du bien }
          location:   { label: Localité }
          price:      { label: Prix / Loyer (€) }
          surface:    { label: Surface (m²) }
      list:
          title: Liste des biens
          display: [=name, location, type, price, created_at]
      filter:  ~
      form:    ~
      edit:
          title: Modifier un bien
      new:
          title: Ajouter un bien
